In [1]:
! pip install nltk

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import DataLoader, Dataset
from nltk.tokenize import word_tokenize
import nltk
from nltk.tokenize import sent_tokenize



In [3]:
document ="""The Impact of Technology on Modern Society Technology has become an integral part of human civilization, shaping how we live, work, and communicate. From the early days of the wheel and fire to the modern advancements in artificial intelligence and quantum computing, technology has continuously evolved, transforming societies and industries. This essay explores the profound impact of technology on modern society, discussing its benefits, challenges, and future implications.
The Evolution of Technology

Human civilization has always been driven by innovation. The discovery of fire and the invention of the wheel marked the beginning of technological advancements. The Industrial Revolution introduced mechanization, significantly boosting productivity and transforming economies. The 20th and 21st centuries have seen rapid technological progress, with developments in computing, telecommunications, and medical sciences revolutionizing daily life.

Technology in Communication

One of the most significant impacts of technology is in communication. The invention of the telephone allowed people to communicate over long distances, and the rise of the internet has taken connectivity to a whole new level. Social media platforms, video conferencing, and instant messaging have made it possible for people to stay connected regardless of geographical barriers. The rise of artificial intelligence has further improved communication through chatbots, virtual assistants, and real-time language translation.

Technology in Education

The education sector has undergone a major transformation due to technology. Online learning platforms, digital textbooks, and virtual classrooms have made education more accessible. Students can now learn from anywhere in the world, and teachers can use interactive tools to enhance their lessons. Technologies such as artificial intelligence and virtual reality are making learning more immersive and effective."""


In [4]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [5]:
#tokenize
tokens = word_tokenize(document.lower())
tokens

['the',
 'impact',
 'of',
 'technology',
 'on',
 'modern',
 'society',
 'technology',
 'has',
 'become',
 'an',
 'integral',
 'part',
 'of',
 'human',
 'civilization',
 ',',
 'shaping',
 'how',
 'we',
 'live',
 ',',
 'work',
 ',',
 'and',
 'communicate',
 '.',
 'from',
 'the',
 'early',
 'days',
 'of',
 'the',
 'wheel',
 'and',
 'fire',
 'to',
 'the',
 'modern',
 'advancements',
 'in',
 'artificial',
 'intelligence',
 'and',
 'quantum',
 'computing',
 ',',
 'technology',
 'has',
 'continuously',
 'evolved',
 ',',
 'transforming',
 'societies',
 'and',
 'industries',
 '.',
 'this',
 'essay',
 'explores',
 'the',
 'profound',
 'impact',
 'of',
 'technology',
 'on',
 'modern',
 'society',
 ',',
 'discussing',
 'its',
 'benefits',
 ',',
 'challenges',
 ',',
 'and',
 'future',
 'implications',
 '.',
 'the',
 'evolution',
 'of',
 'technology',
 'human',
 'civilization',
 'has',
 'always',
 'been',
 'driven',
 'by',
 'innovation',
 '.',
 'the',
 'discovery',
 'of',
 'fire',
 'and',
 'the',
 '

In [6]:
#building the vacab
vocab={"<unk>":0}#takay unkowns ke liye ye kaam main ajay
#vocab ko manay dictionary es liye banaya hai takay main baad main har ek word se indext nikal pau (English to text)
countofTokens=Counter(tokens)
countofTokens

Counter({'the': 20,
         'impact': 2,
         'of': 14,
         'technology': 9,
         'on': 2,
         'modern': 3,
         'society': 2,
         'has': 6,
         'become': 1,
         'an': 1,
         'integral': 1,
         'part': 1,
         'human': 2,
         'civilization': 2,
         ',': 20,
         'shaping': 1,
         'how': 1,
         'we': 1,
         'live': 1,
         'work': 1,
         'and': 16,
         'communicate': 2,
         '.': 15,
         'from': 2,
         'early': 1,
         'days': 1,
         'wheel': 2,
         'fire': 2,
         'to': 6,
         'advancements': 2,
         'in': 6,
         'artificial': 3,
         'intelligence': 3,
         'quantum': 1,
         'computing': 2,
         'continuously': 1,
         'evolved': 1,
         'transforming': 2,
         'societies': 1,
         'industries': 1,
         'this': 1,
         'essay': 1,
         'explores': 1,
         'profound': 1,
         'discussing': 1,
  

In [7]:
#ab jin ka token 1 hai unique hain unse hamne vacab bnani hai
countofTokens.keys()

dict_keys(['the', 'impact', 'of', 'technology', 'on', 'modern', 'society', 'has', 'become', 'an', 'integral', 'part', 'human', 'civilization', ',', 'shaping', 'how', 'we', 'live', 'work', 'and', 'communicate', '.', 'from', 'early', 'days', 'wheel', 'fire', 'to', 'advancements', 'in', 'artificial', 'intelligence', 'quantum', 'computing', 'continuously', 'evolved', 'transforming', 'societies', 'industries', 'this', 'essay', 'explores', 'profound', 'discussing', 'its', 'benefits', 'challenges', 'future', 'implications', 'evolution', 'always', 'been', 'driven', 'by', 'innovation', 'discovery', 'invention', 'marked', 'beginning', 'technological', 'industrial', 'revolution', 'introduced', 'mechanization', 'significantly', 'boosting', 'productivity', 'economies', '20th', '21st', 'centuries', 'have', 'seen', 'rapid', 'progress', 'with', 'developments', 'telecommunications', 'medical', 'sciences', 'revolutionizing', 'daily', 'life', 'communication', 'one', 'most', 'significant', 'impacts', 'is'

In [8]:
for tokens in countofTokens.keys():
    if tokens not in vocab:
        vocab[tokens]=len(vocab)#token is value and vocab is key i used len because of count karne ke liye har ek word vocab main aye or count aye
vocab

{'<unk>': 0,
 'the': 1,
 'impact': 2,
 'of': 3,
 'technology': 4,
 'on': 5,
 'modern': 6,
 'society': 7,
 'has': 8,
 'become': 9,
 'an': 10,
 'integral': 11,
 'part': 12,
 'human': 13,
 'civilization': 14,
 ',': 15,
 'shaping': 16,
 'how': 17,
 'we': 18,
 'live': 19,
 'work': 20,
 'and': 21,
 'communicate': 22,
 '.': 23,
 'from': 24,
 'early': 25,
 'days': 26,
 'wheel': 27,
 'fire': 28,
 'to': 29,
 'advancements': 30,
 'in': 31,
 'artificial': 32,
 'intelligence': 33,
 'quantum': 34,
 'computing': 35,
 'continuously': 36,
 'evolved': 37,
 'transforming': 38,
 'societies': 39,
 'industries': 40,
 'this': 41,
 'essay': 42,
 'explores': 43,
 'profound': 44,
 'discussing': 45,
 'its': 46,
 'benefits': 47,
 'challenges': 48,
 'future': 49,
 'implications': 50,
 'evolution': 51,
 'always': 52,
 'been': 53,
 'driven': 54,
 'by': 55,
 'innovation': 56,
 'discovery': 57,
 'invention': 58,
 'marked': 59,
 'beginning': 60,
 'technological': 61,
 'industrial': 62,
 'revolution': 63,
 'introduced':

In [9]:
len(vocab)

164

In [10]:
import re

def split_into_sentences(text):
    # This regular expression looks for punctuation that typically ends a sentence,
    # followed by one or more whitespace characters.
    pattern = r'(?<=[.!?])\s+'
    sentences = re.split(pattern, text)
    return sentences

In [11]:
input_sentences = split_into_sentences(document)
input_sentences

['The Impact of Technology on Modern Society Technology has become an integral part of human civilization, shaping how we live, work, and communicate.',
 'From the early days of the wheel and fire to the modern advancements in artificial intelligence and quantum computing, technology has continuously evolved, transforming societies and industries.',
 'This essay explores the profound impact of technology on modern society, discussing its benefits, challenges, and future implications.',
 'The Evolution of Technology\n\nHuman civilization has always been driven by innovation.',
 'The discovery of fire and the invention of the wheel marked the beginning of technological advancements.',
 'The Industrial Revolution introduced mechanization, significantly boosting productivity and transforming economies.',
 'The 20th and 21st centuries have seen rapid technological progress, with developments in computing, telecommunications, and medical sciences revolutionizing daily life.',
 'Technology in

In [12]:
for sentence in input_sentences:
    print(word_tokenize(sentence.lower()))

['the', 'impact', 'of', 'technology', 'on', 'modern', 'society', 'technology', 'has', 'become', 'an', 'integral', 'part', 'of', 'human', 'civilization', ',', 'shaping', 'how', 'we', 'live', ',', 'work', ',', 'and', 'communicate', '.']
['from', 'the', 'early', 'days', 'of', 'the', 'wheel', 'and', 'fire', 'to', 'the', 'modern', 'advancements', 'in', 'artificial', 'intelligence', 'and', 'quantum', 'computing', ',', 'technology', 'has', 'continuously', 'evolved', ',', 'transforming', 'societies', 'and', 'industries', '.']
['this', 'essay', 'explores', 'the', 'profound', 'impact', 'of', 'technology', 'on', 'modern', 'society', ',', 'discussing', 'its', 'benefits', ',', 'challenges', ',', 'and', 'future', 'implications', '.']
['the', 'evolution', 'of', 'technology', 'human', 'civilization', 'has', 'always', 'been', 'driven', 'by', 'innovation', '.']
['the', 'discovery', 'of', 'fire', 'and', 'the', 'invention', 'of', 'the', 'wheel', 'marked', 'the', 'beginning', 'of', 'technological', 'advanc

In [13]:
def text_to_index(sentence,vocab):
  numeric_sentence=[]

  for token in sentence:
    if token in vocab:
      numeric_sentence.append(vocab[token])
    else:
      numeric_sentence.append(vocab["<unk>"])#matlab 0
  return numeric_sentence

In [14]:
input_numerical_sentences =[]
for sentences in input_sentences:
  input_numerical_sentences.append(text_to_index(word_tokenize(sentences.lower()),vocab))
input_numerical_sentences

[[1,
  2,
  3,
  4,
  5,
  6,
  7,
  4,
  8,
  9,
  10,
  11,
  12,
  3,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  15,
  20,
  15,
  21,
  22,
  23],
 [24,
  1,
  25,
  26,
  3,
  1,
  27,
  21,
  28,
  29,
  1,
  6,
  30,
  31,
  32,
  33,
  21,
  34,
  35,
  15,
  4,
  8,
  36,
  37,
  15,
  38,
  39,
  21,
  40,
  23],
 [41,
  42,
  43,
  1,
  44,
  2,
  3,
  4,
  5,
  6,
  7,
  15,
  45,
  46,
  47,
  15,
  48,
  15,
  21,
  49,
  50,
  23],
 [1, 51, 3, 4, 13, 14, 8, 52, 53, 54, 55, 56, 23],
 [1, 57, 3, 28, 21, 1, 58, 3, 1, 27, 59, 1, 60, 3, 61, 30, 23],
 [1, 62, 63, 64, 65, 15, 66, 67, 68, 21, 38, 69, 23],
 [1,
  70,
  21,
  71,
  72,
  73,
  74,
  75,
  61,
  76,
  15,
  77,
  78,
  31,
  35,
  15,
  79,
  15,
  21,
  80,
  81,
  82,
  83,
  84,
  23],
 [4, 31, 85, 86, 3, 1, 87, 88, 89, 3, 4, 90, 31, 85, 23],
 [1,
  58,
  3,
  1,
  91,
  92,
  93,
  29,
  22,
  94,
  95,
  96,
  15,
  21,
  1,
  97,
  3,
  1,
  98,
  8,
  99,
  100,
  29,
  101,
  102,
  103,
  104,
  23],
 [10

In [15]:
len(input_numerical_sentences)

15

In [16]:
for sentence in input_numerical_sentences:
  for i in range(1,len(sentence)):
    print(sentence[:i+1])


[1, 2]
[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 4]
[1, 2, 3, 4, 5, 6, 7, 4, 8]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16, 17]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16, 17, 18]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16, 17, 18, 19]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16, 17, 18, 19, 15]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16, 17, 18, 19, 15, 20]
[1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16, 17, 18, 19

In [17]:
training_seq=[]
for sentence in input_numerical_sentences:
  for i in range(1,len(sentence)):
    training_seq.append(sentence[:i+1])
training_seq

[[1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5, 6],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7, 4],
 [1, 2, 3, 4, 5, 6, 7, 4, 8],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16, 17],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16, 17, 18],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16, 17, 18, 19],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16, 17, 18, 19, 15],
 [1,
  2,
  3,
  4,
  5,
  6,
  7,
  4,
  8,
  9,
  10,
  11,
  12,
  3,
  13,
  14,
  15,
  16,
  17,
  18,
  1

In [18]:
training_seq[:25]

[[1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5, 6],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7, 4],
 [1, 2, 3, 4, 5, 6, 7, 4, 8],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16, 17],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16, 17, 18],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16, 17, 18, 19],
 [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 11, 12, 3, 13, 14, 15, 16, 17, 18, 19, 15],
 [1,
  2,
  3,
  4,
  5,
  6,
  7,
  4,
  8,
  9,
  10,
  11,
  12,
  3,
  13,
  14,
  15,
  16,
  17,
  18,
  1

In [19]:
len(training_seq) #287 rows pay train hoga

287

In [20]:
#pre padding
max_len=max([len(seq) for seq in training_seq])
max_len

30

In [21]:
for sequnces in training_seq:
 print( [0]*(max_len-len(sequnces))+sequnces)


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 4]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 4, 8]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 4, 8, 9]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10, 

In [22]:
padded_training_seq =[]
for sequnces in training_seq:
  padded_training_seq.append([0]*(max_len-len(sequnces))+sequnces)


In [23]:
padded_training_seq[:5]

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5,
  6]]

In [24]:
padded_training_seq=torch.tensor(padded_training_seq,dtype=torch.long)
padded_training_seq

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        ...,
        [  0,   0,   0,  ..., 141, 162,  21],
        [  0,   0,   0,  ..., 162,  21, 163],
        [  0,   0,   0,  ...,  21, 163,  23]])

In [25]:
padded_training_seq.shape#30cols

torch.Size([287, 30])

In [26]:
X=padded_training_seq[:,:-1]
y=padded_training_seq[:,-1]

In [27]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        ...,
        [  0,   0,   0,  ..., 137, 141, 162],
        [  0,   0,   0,  ..., 141, 162,  21],
        [  0,   0,   0,  ..., 162,  21, 163]])

In [28]:
y

tensor([  2,   3,   4,   5,   6,   7,   4,   8,   9,  10,  11,  12,   3,  13,
         14,  15,  16,  17,  18,  19,  15,  20,  15,  21,  22,  23,   1,  25,
         26,   3,   1,  27,  21,  28,  29,   1,   6,  30,  31,  32,  33,  21,
         34,  35,  15,   4,   8,  36,  37,  15,  38,  39,  21,  40,  23,  42,
         43,   1,  44,   2,   3,   4,   5,   6,   7,  15,  45,  46,  47,  15,
         48,  15,  21,  49,  50,  23,  51,   3,   4,  13,  14,   8,  52,  53,
         54,  55,  56,  23,  57,   3,  28,  21,   1,  58,   3,   1,  27,  59,
          1,  60,   3,  61,  30,  23,  62,  63,  64,  65,  15,  66,  67,  68,
         21,  38,  69,  23,  70,  21,  71,  72,  73,  74,  75,  61,  76,  15,
         77,  78,  31,  35,  15,  79,  15,  21,  80,  81,  82,  83,  84,  23,
         31,  85,  86,   3,   1,  87,  88,  89,   3,   4,  90,  31,  85,  23,
         58,   3,   1,  91,  92,  93,  29,  22,  94,  95,  96,  15,  21,   1,
         97,   3,   1,  98,   8,  99, 100,  29, 101, 102, 103, 1

In [29]:
class CustomDataset(Dataset):
  def __init__(self,X,y):
    self.X=X
    self.y=y

  def __len__(self):
    return self.X.shape[0]

  def __getitem__(self,idx):
    return self.X[idx],self.y[idx]

In [30]:
dataset=CustomDataset(X,y)


In [31]:
len(dataset)

287

In [32]:
dataset[2]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 2, 3]),
 tensor(4))

In [33]:
dataloader=DataLoader(dataset,batch_size=32,shuffle=True)#means 32 sentences will train at once



In [34]:
for input,output in dataloader:
   print(input,output)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   1,  58,   3,   1,  91,
          92,  93,  29,  22,  94,  95,  96,  15,  21,   1,  97,   3,   1,  98,
           8],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,  57,   3,  28,
          21],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           1],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   1,  97,   3,  32,  33,
           8],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0, 136, 137, 107,  15, 138, 139,  15,  21, 125, 140,
          73],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [35]:
X.shape#287 sentences and 29 words so lstm 29 dafa chalay ga or jo bi batch size utna parally chalay ga

torch.Size([287, 29])

In [36]:
#architecture
class LSTMModel(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding=nn.Embedding(vocab_size,100)#vector 100
    self.lstm=nn.LSTM(100,150,batch_first=True)
    self.fc=nn.Linear(150,vocab_size)

  def forward(self,x):
    embedded=self.embedding(x)
    intermediate_hidden_states,(final_hidden_state,final_cell_state)=self.lstm(embedded)
    output=self.fc(final_hidden_state.squeeze(0))
    return output


In [37]:
#below is only for understanding not in code
len(vocab)

164

In [38]:
X=nn.Embedding(164,100)
y=nn.LSTM(100,150,batch_first=True)
z=nn.Linear(150,164)


In [39]:
dataset[0][0].shape

torch.Size([29])

In [40]:
dataset[0][0].unsqueeze(0).shape

torch.Size([1, 29])

In [41]:
a=dataset[0][0].unsqueeze(0)

In [42]:
X(a).shape

torch.Size([1, 29, 100])

In [43]:
b=X(a)

In [44]:
c,d =y(b)


In [45]:
c.shape #150 is nurral network nodes

torch.Size([1, 29, 150])

In [46]:
d

(tensor([[[-8.4183e-02, -1.1116e-01,  2.2057e-01,  1.2289e-01,  9.7330e-02,
           -3.7433e-04,  2.2957e-02,  8.4480e-02, -1.4053e-01,  2.1341e-01,
            2.7172e-01, -8.6469e-02,  6.8432e-02, -3.5833e-01, -2.0845e-01,
           -7.3120e-02, -1.2447e-01,  2.8798e-01,  5.3618e-02,  7.4790e-02,
            1.8785e-01,  2.6947e-01, -3.5939e-01,  1.5783e-01, -3.7239e-01,
            3.4494e-02, -1.1835e-01,  2.8938e-02,  8.9679e-02, -2.5441e-01,
            8.2397e-02,  9.0080e-02,  1.2863e-02,  5.6000e-02,  1.0035e-01,
           -7.2700e-02, -9.0013e-02, -1.7883e-01, -1.6887e-01,  2.1961e-02,
           -1.0090e-01,  2.2077e-01,  2.1240e-01,  3.2479e-01, -7.1505e-02,
           -2.6179e-02,  5.0399e-02, -2.4166e-01,  6.1450e-02, -2.0680e-01,
            2.2510e-01,  5.7224e-02,  3.0474e-01, -4.6007e-02,  4.1691e-03,
           -1.2288e-01, -1.2894e-01,  1.5460e-01,  1.4840e-01, -7.8644e-02,
           -3.0345e-01, -9.3369e-02, -5.2828e-02,  4.7886e-02,  6.5105e-02,
            

In [47]:
#ye ek touple hai  d tou unpack karo
e,f=d

In [48]:
f.shape

torch.Size([1, 1, 150])

In [49]:
z(f.squeeze(0)).shape
#now the real code starts
#begin


torch.Size([1, 164])

In [50]:
model =LSTMModel(len(vocab))

In [51]:
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")


In [52]:
model.to(device)

LSTMModel(
  (embedding): Embedding(164, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=164, bias=True)
)

In [53]:
epochs=50
learning_rate=0.001
criteria=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)


In [54]:
#training loop
for epoch in range(epochs):
  total_loss=0
  for batch_x,batch_y in dataloader:
    batch_x,batch_y=batch_x.to(device), batch_y.to(device)
    optimizer.zero_grad()
    output=model(batch_x)
    loss=criteria(output,batch_y)
    loss.backward()
    optimizer.step()
    total_loss=total_loss+loss.item()

  print(f"epoch:{epoch+1},loss:{total_loss:.4f}")

epoch:1,loss:45.8730
epoch:2,loss:44.3705
epoch:3,loss:42.1747
epoch:4,loss:39.5271
epoch:5,loss:36.6261
epoch:6,loss:34.1305
epoch:7,loss:31.4809
epoch:8,loss:28.9746
epoch:9,loss:26.4530
epoch:10,loss:24.1604
epoch:11,loss:21.7693
epoch:12,loss:19.6101
epoch:13,loss:17.4699
epoch:14,loss:15.6590
epoch:15,loss:14.0225
epoch:16,loss:12.5327
epoch:17,loss:11.2496
epoch:18,loss:10.0906
epoch:19,loss:8.9439
epoch:20,loss:8.0410
epoch:21,loss:7.2535
epoch:22,loss:6.5345
epoch:23,loss:5.9251
epoch:24,loss:5.3539
epoch:25,loss:4.9026
epoch:26,loss:4.4886
epoch:27,loss:4.1396
epoch:28,loss:3.8344
epoch:29,loss:3.5486
epoch:30,loss:3.3002
epoch:31,loss:3.0782
epoch:32,loss:2.8757
epoch:33,loss:2.7148
epoch:34,loss:2.5641
epoch:35,loss:2.4146
epoch:36,loss:2.2831
epoch:37,loss:2.1963
epoch:38,loss:2.0872
epoch:39,loss:1.9831
epoch:40,loss:1.9014
epoch:41,loss:1.8289
epoch:42,loss:1.7575
epoch:43,loss:1.6784
epoch:44,loss:1.6380
epoch:45,loss:1.5790
epoch:46,loss:1.5094
epoch:47,loss:1.4549
epoc

In [61]:
#prediction
def pridiction(model,vocab,text):
  #tokenize
  tokenized_text =word_tokenize(text.lower())
  #text->num_indexes
  numerical_text=text_to_index(tokenized_text,vocab)

  #padding
  padded_text=torch.tensor([0]*(29-len(numerical_text))+numerical_text,dtype=torch.long).unsqueeze(0)
  #send to model
  output=model(padded_text)
  #pridicted index
  value,index=torch.max(output,dim=1)
  #merge with text
  return text +" "+list(vocab.keys())[index]

In [62]:
pridiction(model,vocab,"The Impact of technology on")

'The Impact of technology on modern'

In [64]:
import time
num_tokens=10
input_texr="The Evolution of Technology"
for i in range(num_tokens):
  output_text=pridiction(model,vocab,input_texr)
  print(output_text)
  input_texr=output_text
  time.sleep(0.5)



The Evolution of Technology human
The Evolution of Technology human civilization
The Evolution of Technology human civilization has
The Evolution of Technology human civilization has always
The Evolution of Technology human civilization has always been
The Evolution of Technology human civilization has always been driven
The Evolution of Technology human civilization has always been driven by
The Evolution of Technology human civilization has always been driven by innovation
The Evolution of Technology human civilization has always been driven by innovation .
The Evolution of Technology human civilization has always been driven by innovation . .
